
version: "3.9"
services:
  app-front:
    container_name: app-front
    build: ./front
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    networks:
      - dern-app
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules # volume trick

  app-api:
    container_name: app-api
    build: ./api
    ports:
      - "3001:3001"
    networks:
      - dern-app
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules # volume trick
    depends_on:
      - dynamodb

  dynamodb:
    container_name: dynamodb-local
    hostname: dynamodblocal
    image: amazon/dynamodb-local:latest
    # -sharedDb : ない場合は、myaccesskeyid_region.dbとなる
    # -dbPath :永続化するデータのパスを指定(volumeのパス)
    # -inMemory : データはメモリ内に展開され、コンテナを停止・削除するとデータも破棄される
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    # admin
    ports:
      - "8000:8000"
    networks:
      - dern-app
    volumes:
      - ./dynamodb-local-data:/data
    expose:
      - "8000"

  # MongoDB Atlasを一旦使う。
  # mongo-db:
  #   container_name: mongo-db
  #   image: mongo:latest8000:
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=mng_user
  #     - MONGO_INITDB_ROOT_PASSWORD=mng_pw
  #     # - MONGO_INITDB_DATABASE=chat
  #   networks:
  #     - dern-app
  #   volumes:
  #     - mongo-data:/data/db

  # volumes:
  #   mongo-data:
  #     driver: local


networks:
  dern-app:
    driver: bridge

volumes:
  dynamodb-local-data: